Repository prabirshrestha/vim-lsp, pull requests merged in 2018-12, with the labels that each got.

#208 Handle lower-case drive-letter
  autoload/lsp/utils.vim
Labels: bug

#222 Check result is null
  autoload/lsp/omni.vim
Labels: bug

#223 add basic .travis.yml
  .travis.yml
  plugin/lsp.vim
Labels: enhancement

#224 fix lint issues and enable linting for autoload folder
  .travis.yml
  autoload/lsp.vim
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim/diagnostics/echo.vim
  autoload/lsp/ui/vim/output.vim
  autoload/lsp/ui/vim/signs.vim
Labels: duplicate

#225 testing initial windows ci
  .travis.yml
Labels: infrastructure

#227 download neovim tar.gz
  .travis.yml
Labels: infrastructure
