Repository prabirshrestha/vim-lsp, pull requests merged in 2018-03, with the labels that each got.

#113 Print error message when server fails to initialize
  autoload/lsp.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/utils.vim
Labels: waiting for reply

#107 Percent-decode uri from language server to fix issue #106
  autoload/lsp/utils.vim
Labels: enhancement, waiting for reply

#118 add support for document changes rename
  autoload/lsp/ui/vim.vim
Labels: enhancement

#120 respect insertTextFormat and make lsp#omni#format_completion_item() public
  autoload/lsp/omni.vim
Labels: bug, enhancement

#122 bring back custom sign and fix sign when icon is not defined
  README.md
  autoload/lsp/ui/vim/signs.vim
  plugin/lsp.vim
Labels: enhancement
