Repository prabirshrestha/vim-lsp, pull requests merged in 2019-12, with the labels that each got.

#553 If the hover response has only empty string content, we don't display anything
  autoload/lsp/ui/vim/output.vim
Labels: bug

#587 Jump to next/previous diagnostics other than error diagnostics
  README.md
  autoload/lsp/ui/vim/diagnostics.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#602 Print color statuses
  autoload/lsp.vim
  plugin/lsp.vim
Labels: enhancement

#604 Add :LspStopServer
  autoload/lsp/ui/vim.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: documentation

#608 add reviewdog vint github actions
  .github/workflows/reviewdog.yml
  .vintrc.yaml
Labels: infrastructure

#610 remove python/pip/vint from travis.yml
  .travis.yml
Labels: infrastructure

#611 use bionic linux and test against linux vim
  .travis.yml
Labels: infrastructure

#612 initial github actions workflow for windows
  .github/workflows/reviewdog.yml
  .github/workflows/windows_vim.yml
Labels: infrastructure

#617 add github workflow for windows_neovim
  .github/workflows/windows_neovim.yml
  .github/workflows/windows_vim.yml
Labels: infrastructure

#618 added mac neovim github actions
  .github/workflows/mac_neovim.yml
Labels: infrastructure

#620 add neovim linux github actions
  .github/workflows/linux_neovim.yml
Labels: infrastructure

#621 initial linux vim github ci
  .github/workflows/linux_vim.yml
  .github/workflows/windows_vim.yml
Labels: infrastructure

#622 remove travis.yml
  .travis.yml
Labels: infrastructure

#506 Fix an issue in highlighting of references.
  autoload/lsp/ui/vim/references.vim
Labels: bug

#623 add official link to vim-lsp-settings instructions
  README.md
  doc/vim-lsp.txt
Labels: documentation

#626 escape \r in preview
  autoload/lsp/ui/vim/output.vim
Labels: bug

#627 document lsp_buffer_enabled in README.md
  README.md
Labels: documentation

#629 no text document did save delay by default
  autoload/lsp.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: bug

#464 Implement semantic highlighting
  README.md
  autoload/lsp.vim
  autoload/lsp/capabilities.vim
  autoload/lsp/ui/vim/semantic.vim
  autoload/lsp/utils.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/utils.vimspec
Labels: enhancement

#630 default hierarchicalDocumentSymbolSupport to false for documentSymbol
  autoload/lsp.vim
Labels: enhancement

#631 support hierarchical document symbol even if we don't explicilty set it to true
  autoload/lsp/ui/vim/utils.vim
Labels: enhancement

#639 change reviewdog vint reporter to github-pr-reviewer
  .github/workflows/reviewdog.yml
Labels: infrastructure
