Repository prabirshrestha/vim-lsp, pull requests merged in 2019-02, with the labels that each got.

#299 default g:lsp_use_event_queue to 1
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#271 Skip loading on old versions of vim without json
  plugin/lsp.vim
Labels: enhancement

#253 Prepare range for rename
  autoload/lsp/capabilities.vim
  autoload/lsp/ui/vim.vim
Labels: bug, enhancement

#283 Add format-range-sync
  autoload/lsp/ui/vim.vim
  plugin/lsp.vim
Labels: enhancement

#302 If the user has "fixendofline" set, append a blank line to preserve the EOF newline
  autoload/lsp.vim
  autoload/lsp/utils/buffer.vim
  test/lsp/utils/buffer.vimspec
Labels: bug

#316 Fix mapping not to use <expr>
  plugin/lsp.vim
Labels: bug

#294 Redo diagnostics
  autoload/lsp/ui/vim/signs.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement
