Repository prabirshrestha/vim-lsp, pull requests merged in 2019-01, with the labels that each got.

#229 Show details (type info, etc.) in completion menu
  autoload/lsp/omni.vim
Labels: enhancement

#205 Handle showcmd enabled
  autoload/lsp/utils.vim
Labels: waiting for reply

#197 Add flag to disable diagnostics
  README.md
  autoload/lsp.vim
  autoload/lsp/ui/vim/diagnostics.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#236 Check result is null
  autoload/lsp/omni.vim
Labels: bug

#240 add themis tests
  .travis.yml
  test/.themisrc
  test/lsp/utils.vimspec
Labels: enhancement

#242 add missing :LspTypeDefinition
  plugin/lsp.vim
Labels: enhancement

#273 Fix race while switching buffer
  autoload/lsp.vim
Labels: bug
