Repository prabirshrestha/vim-lsp, pull requests merged in 2020-09, with the labels that each got.

#899 Callbag materialize
  autoload/lsp.vim
  autoload/lsp/callbag.vim
  autoload/lsp/internal/diagnostics/echo.vim
  autoload/lsp/internal/diagnostics/float.vim
  autoload/lsp/internal/highlight_references.vim
  plugin/lsp.vim
Labels: bug, enhancement

#906 Load `retriggerCharacters` for signature help.
  autoload/lsp/capabilities.vim
Labels: enhancement

#910 doc: remove a stray line from echo_delay
  doc/vim-lsp.txt
Labels: documentation
