Repository prabirshrestha/vim-lsp, pull requests merged in 2020-05, with the labels that each got.

#797 Add example for g:lsp_get_vim_completion_item
  doc/vim-lsp.txt
Labels: documentation

#770 Jumping to diagnostics with command args '-nowrap'
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/utils.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#811 Add ability to set unique highlight group for virtual text
  README.md
  autoload/lsp/ui/vim/virtual.vim
  doc/vim-lsp.txt
Labels: enhancement

#822 improve perf by not calling get_position() in lsp#omni#default_get_vim_completion_item if already exists
  autoload/lsp/omni.vim
Labels: perf

#824 [perf] add g:lsp_get_vim_completion_item_set_kind to enable or disable kind
  autoload/lsp/omni.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/omni.vimspec
Labels: perf

#815 Add support for the tagfunc option
  README.md
  autoload/lsp.vim
  autoload/lsp/client.vim
  autoload/lsp/omni.vim
  autoload/lsp/tag.vim
  autoload/lsp/ui/vim/utils.vim
  autoload/lsp/utils.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#828 Add config.diagnostics to disable diagnostics per server
  autoload/lsp.vim
  doc/vim-lsp.txt
Labels: enhancement
