Repository prabirshrestha/vim-lsp, pull requests merged in 2020-06, with the labels that each got.

#834 add lsp#omni#get_vim_completion_items()
  autoload/lsp/omni.vim
Labels: enhancement, perf

#812 Add checks for cmdwin
  autoload/lsp/ui/vim/output.vim
Labels: bug

#813 Fix peek {definition,declaration} in files with whitespaces in pathnames
  autoload/lsp/ui/vim.vim
Labels: bug

#752 Changed Quickfix list behaviour
  autoload/lsp/ui/vim.vim
Labels: bug, enhancement

#835 optimize lsp#omni#get_vim_completion_items()
  autoload/lsp/omni.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/omni.vimspec
Labels: enhancement, perf

#507 [WIP] Popup documentation
  autoload/lsp.vim
  autoload/lsp/ui/vim/documentation.vim
  autoload/lsp/ui/vim/output.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#845 use callbag
  autoload/lsp.vim
  autoload/lsp/callbag.vim
  autoload/lsp/internal/diagnostics.vim
  autoload/lsp/internal/diagnostics/echo.vim
  autoload/lsp/ui/vim/diagnostics/echo.vim
Labels: enhancement

#847 use allowlist and blocklist instead
  README.md
  autoload/lsp.vim
  autoload/lsp/omni.vim
  autoload/lsp/tag.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/ui/vim/code_action.vim
  autoload/lsp/ui/vim/code_lens.vim
  autoload/lsp/ui/vim/folding.vim
  autoload/lsp/ui/vim/hover.vim
  autoload/lsp/ui/vim/references.vim
  autoload/lsp/ui/vim/semantic.vim
  autoload/lsp/ui/vim/signature_help.vim
  doc/vim-lsp.txt
  minimal.vimrc
Labels: enhancement

#851 Lua arrays are now one based starting v8.2.1066
  autoload/lsp/utils/diff.vim
Labels: enhancement

#852 Doesn't working show preview due to window size.
  autoload/lsp/ui/vim/documentation.vim
Labels: bug

#859 fix Invalid window id when calling close preview (fixes #858)
  autoload/lsp/ui/vim/output.vim
Labels: bug

#679 Text props for reference highlights
  autoload/lsp/ui/vim/references.vim
  autoload/lsp/ui/vim/semantic.vim
Labels: enhancement
