Repository prabirshrestha/vim-lsp, pull requests merged in 2020-12, with the labels that each got.

#948 Fix typo
  doc/vim-lsp.txt
Labels: documentation

#949 support for non-boolean values in serverCapabilities
  autoload/lsp/capabilities.vim
Labels: bug

#951 update callbag to 9108df10d721c04a8908a391dde14aeabacc422d
  autoload/lsp/callbag.vim
Labels: enhancement

#956 use callbag to implement document format with timeout
  README.md
  autoload/lsp.vim
  autoload/lsp/internal/document_formatting.vim
  autoload/lsp/internal/document_range_formatting.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/utils/args.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#957 add lsp#utils#buffer#get_indent_size()
  autoload/lsp/internal/document_formatting.vim
  autoload/lsp/internal/document_range_formatting.vim
  autoload/lsp/utils/buffer.vim
  test/lsp/utils/buffer.vimspec
Labels: enhancement

#958 update vim-themis to v1.5.5
  .github/workflows/linux_neovim.yml
  .github/workflows/linux_vim.yml
  .github/workflows/mac_neovim.yml
  .github/workflows/windows_neovim.yml
  .github/workflows/windows_vim.yml
Labels: infrastructure

#960 always add range for diagnostics test
  test/lsp/ui/vim/diagnostics.vimspec
Labels: bug

#962 use reporter spec by default in themis
  .github/workflows/linux_neovim.yml
  .github/workflows/linux_vim.yml
  .github/workflows/mac_neovim.yml
  .github/workflows/windows_neovim.yml
  .github/workflows/windows_vim.yml
  test/.themisrc
Labels: infrastructure

#959 [WIP] do not merge: integration tests with language servers
  .github/workflows/linux_neovim.yml
  .github/workflows/linux_vim.yml
  .github/workflows/mac_neovim.yml
  README.md
  autoload/lsp/ui/vim/highlights.vim
  autoload/lsp/ui/vim/virtual.vim
  test/.themisrc
  test/integration/rust/document_formatting.vimspec
  test/lsp/ui/vim/diagnostics.vimspec
  test/testproject-rust/.gitignore
  test/testproject-rust/Cargo.lock
  test/testproject-rust/Cargo.toml
  test/testproject-rust/src/documentformat.rs
  test/testproject-rust/src/main.rs
  test/utils/autoload/lsp/test.vim
Labels: infrastructure

#963 add addtionalTextEdits for resolve support capability
  autoload/lsp.vim
Labels: enhancement

#964 set synchornization client capabilities
  autoload/lsp.vim
Labels: enhancement

#965 add hover client capabilities
  autoload/lsp.vim
Labels: enhancement

#966 explicitly set dynamic registration to false and sort
  autoload/lsp.vim
Labels: enhancement

#967 add references capabilities
  autoload/lsp.vim
Labels: enhancement

#969 added more dynamicRegistration set to false
  autoload/lsp.vim
Labels: enhancement

#970 add support for window.workDoneProgress client capabilities - $/progress reports
  autoload/lsp.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#971 send clientInfo as part of InitializeParams
  autoload/lsp.vim
Labels: enhancement

#972 add goto definition integration tests for same file
  test/integration/rust/document_definition.vimspec
  test/integration/rust/document_formatting.vimspec
  test/testproject-rust/src/calc/add.rs
  test/testproject-rust/src/calc/mod.rs
  test/testproject-rust/src/documentdefinition.rs
  test/testproject-rust/src/main.rs
  test/utils/autoload/lsp/test.vim
Labels: tests

#953 Convert lowercase drive letters to uppercase
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/utils.vim
  test/lsp/utils.vimspec
Labels: bug

#976 fix LspNextReference
  autoload/lsp/internal/document_highlight.vim
  plugin/lsp.vim
Labels: bug

#980 add $/vimlsp/lsp_server_exit notification to the stream
  autoload/lsp.vim
  doc/vim-lsp.txt
Labels: enhancement

#978 add internal/diagnostics/state.vim
  autoload/lsp/internal/diagnostics.vim
  autoload/lsp/internal/diagnostics/state.vim
  test/lsp/internal/diagnostics/state.vimspec
Labels: enhancement

#981 add buffer state of disabled diagnostics state
  autoload/lsp/internal/diagnostics/state.vim
  test/lsp/internal/diagnostics/state.vimspec
Labels: enhancement

#983 use buf var for buffer level diagnostics enabled flag
  autoload/lsp/internal/diagnostics/state.vim
Labels: enhancement

#984 fix typo: diagnsotics & disable
  autoload/lsp/internal/diagnostics.vim
Labels: bug

#982 Diagnostics for all buffers
  autoload/lsp/internal/diagnostics/document_diagnostics_command.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/ui/vim/utils.vim
  autoload/lsp/utils/args.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/internal/diagnostics/document_diagnostics_command.vimspec
  test/testproject-rust/src/documentdiagnostics.rs
Labels: enhancement

#986 check for nvim float support before using it - fixes #952
  autoload/lsp/ui/vim/output.vim
Labels: bug

#989 Fix tests
  test/lsp/internal/diagnostics/document_diagnostics_command.vimspec
Labels: bug

#991 update neovim ci from 0.4.3 to 0.4.4
  .github/workflows/linux_neovim.yml
  .github/workflows/mac_neovim.yml
  .github/workflows/windows_neovim.yml
Labels: infrastructure

#992 try fix mac neovim ci
  test/integration/rust/document_definition.vimspec
Labels: infrastructure

#990 Revamp virtual text
  README.md
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics.vim
  autoload/lsp/internal/diagnostics/state.vim
  autoload/lsp/internal/diagnostics/virtual_text.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/ui/vim/virtual.vim
  autoload/lsp/utils.vim
  autoload/lsp/utils/position.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#993 add enable check
  autoload/lsp/internal/diagnostics/echo.vim
  autoload/lsp/internal/diagnostics/float.vim
  autoload/lsp/internal/diagnostics/virtual_text.vim
Labels: bug

#994 Diagnostics signs revamp
  README.md
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics.vim
  autoload/lsp/internal/diagnostics/signs.vim
  autoload/lsp/internal/diagnostics/virtual_text.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/ui/vim/signs.vim
  autoload/lsp/utils.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#979 Add I/F to get window/workDoneProgress
  autoload/lsp.vim
  autoload/lsp/internal/work_done_progress.vim
  doc/vim-lsp.txt
  test/lsp/utils/work_done_progress.vimspec
Labels: enhancement
