Repository prabirshrestha/vim-lsp, pull requests merged in 2020-02, with the labels that each got.

#709 clear_all_highlights: check if buffer is loaded
  autoload/lsp/ui/vim/diagnostics/textprop.vim
Labels: bug

#710 document vim-vsnip for snippets
  README.md
  doc/vim-lsp.txt
Labels: documentation

#711 g:lsp_diagnostics_{echo,float}_cursor are NOT exclusive
  autoload/lsp.vim
Labels: enhancement

#713 Add lsp#activate()
  autoload/lsp.vim
Labels: enhancement
