Repository prabirshrestha/vim-lsp, pull requests merged in 2020-04, with the labels that each got.

#794 Small typo
  README.md
Labels: documentation

#776 Add <mods> support for opening new window
  autoload/lsp/ui/vim.vim
  autoload/lsp/utils/location.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#793 Fix error on diagnostics from files not in buffer
  autoload/lsp/ui/vim/highlights.vim
Labels: bug

#759 Add snippet indicator
  autoload/lsp/omni.vim
  test/lsp/omni.vimspec
Labels: enhancement

#788 Support text edit with folding
  autoload/lsp/utils/text_edit.vim
Labels: bug

#774 Fix unneccesary window splits
  autoload/lsp/utils/location.vim
Labels: bug

#672 Support any completion-engine
  autoload/lsp/omni.vim
Labels: enhancement

#802 Avoid autocmd-once for compatibility of VIM8.0
  autoload/lsp.vim
Labels: bug

#806 Fix open_location without mods
  autoload/lsp/utils/location.vim
Labels: bug
