Repository prabirshrestha/vim-lsp, pull requests merged in 2020-01, with the labels that each got.

#641 add initial support for type hierarchy
  LICENSE-THIRD-PARTY
  README.md
  autoload/lsp.vim
  autoload/lsp/capabilities.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/utils/tree.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#642 lsp#utils#tagstack#_update
  autoload/lsp/ui/vim.vim
  autoload/lsp/utils/tagstack.vim
  test/lsp/utils/tagstack.vimspec
Labels: infrastructure

#643 refactor LspTypeHierarchy
  autoload/lsp/ui/vim.vim
  autoload/lsp/utils/buffer.vim
  autoload/lsp/utils/location.vim
  autoload/lsp/utils/position.vim
Labels: infrastructure

#644 add tests for lsp/utils/position.vim
  test/lsp/utils/position.vimspec
Labels: infrastructure

#646 fix _open_lsp_location
  autoload/lsp/utils/buffer.vim
Labels: bug

#645 remove lsp#utils#to_col in favor of lsp#utils#position#_lsp_to_vim
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/ui/vim/diagnostics/textprop.vim
  autoload/lsp/ui/vim/highlights.vim
  autoload/lsp/ui/vim/references.vim
  autoload/lsp/ui/vim/utils.vim
  autoload/lsp/utils.vim
  autoload/lsp/utils/position.vim
  test/lsp/utils.vimspec
Labels: infrastructure

#647 added lsp#utils#location#_lsp_to_vim_list
  autoload/lsp/ui/vim.vim
  autoload/lsp/ui/vim/utils.vim
  autoload/lsp/utils.vim
  autoload/lsp/utils/location.vim
Labels: infrastructure

#648 add lsp#_new_command() and lsp#_last_command()
  autoload/lsp.vim
  autoload/lsp/ui/vim.vim
Labels: infrastructure

#637 Fix CompleteDone
  autoload/lsp.vim
  autoload/lsp/client.vim
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim/completion.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/omni.vimspec
  test/lsp/ui/vim/completion.vimspec
Labels: enhancement

#657 Fixup lsp_location_item_to_vim
  autoload/lsp/utils/location.vim
Labels: bug

#664 Ignore cmdwin
  autoload/lsp.vim
Labels: bug

#663 Improve code action
  autoload/lsp.vim
  autoload/lsp/capabilities.vim
  autoload/lsp/ui/vim.vim
  autoload/lsp/ui/vim/code_action.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/utils/position.vim
  autoload/lsp/utils/range.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
  test/lsp/utils/position.vimspec
  test/lsp/utils/range.vimspec
Labels: enhancement

#665 Fix completion for clangd
  autoload/lsp/omni.vim
  autoload/lsp/utils.vim
Labels: bug

#669 Fix #668
  autoload/lsp/ui/vim/completion.vim
Labels: bug
