Repository prabirshrestha/vim-lsp, pull requests merged in 2021-03, with the labels that each got.

#1068 Fix preview without popup window
  autoload/lsp/ui/vim/output.vim
Labels: bug

#1084 only call prop_remove if we have props to avoid clearing of welcome message for vim
  autoload/lsp/internal/diagnostics/highlights.vim
Labels: bug

#1082 Does not fire lsp_float_closed if floating-window does not exists
  autoload/lsp/ui/vim/output.vim
Labels: bug

#1085 [WIP] add codeaction sign support
  autoload/lsp.vim
  autoload/lsp/internal/document_code_action/signs.vim
  autoload/lsp/internal/document_highlight.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#1095 Use 'label' value when 'insertText' or 'filterText' is falsy
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim/completion.vim
  autoload/lsp/utils/text_edit.vim
  test/lsp/utils/text_edit.vimspec
Labels: bug

#1098 remove flaky integration tests
  test/integration/rust/document_formatting.vimspec
  test/testproject-rust/.gitignore
  test/testproject-rust/Cargo.lock
  test/testproject-rust/Cargo.toml
  test/testproject-rust/src/calc/add.rs
  test/testproject-rust/src/calc/mod.rs
  test/testproject-rust/src/documentdefinition.rs
  test/testproject-rust/src/documentdiagnostics.rs
  test/testproject-rust/src/documentformat.rs
  test/testproject-rust/src/main.rs
Labels: tests

#1099 document diagnostics and code action signs hint
  doc/vim-lsp.txt
Labels: documentation

#1106 add lsp_signature_help_delay to allow users to configure and default to 200
  autoload/lsp/ui/vim/signature_help.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#1105 Add cache for encoding/decoding uri
  autoload/lsp/utils.vim
Labels: perf

#1108 Add integration tests with gopls instead of rust-analyzer
  .github/workflows/linux_neovim.yml
  .github/workflows/linux_vim.yml
  .github/workflows/mac_neovim.yml
  .github/workflows/mac_vim.yml
  .github/workflows/windows_neovim.yml
  .github/workflows/windows_vim.yml
  README.md
  test/integration/go/document_formatting.vimspec
  test/testproject-go/documentformat.go
  test/testproject-rust/.gitignore
  test/testproject-rust/Cargo.lock
  test/testproject-rust/Cargo.toml
  test/testproject-rust/src/calc/add.rs
  test/testproject-rust/src/calc/mod.rs
  test/testproject-rust/src/documentdefinition.rs
  test/testproject-rust/src/documentdiagnostics.rs
  test/testproject-rust/src/documentformat.rs
  test/testproject-rust/src/main.rs
  test/utils/autoload/lsp/test.vim
Labels: tests

#1117 update async.vim to 0fb846e1eb3c2bf04d52a57f41088afb3395212e for perf on stdout/stderr
  autoload/lsp/utils/job.vim
Labels: perf

#1119 Include command argument labels in Code Lens item's text (fix #1118)
  autoload/lsp/internal/ui/quickpick.vim
  autoload/lsp/ui/vim/code_lens.vim
  test/lsp/ui/vim/code_lens.vimspec
Labels: enhancement

#1100 apply markdown for output
  autoload/lsp/ui/vim/output.vim
Labels: bug
