Repository prabirshrestha/vim-lsp, pull requests merged in 2021-05, with the labels that each got.

#1162 Fix typo.
  doc/vim-lsp.txt
Labels: documentation

#1174 add border for documention popup for vim
  autoload/lsp/internal/completion/documentation.vim
  autoload/vital/_lsp/VS/Vim/Syntax/Markdown.vim
  autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim
Labels: enhancement

#1175 perf: parse array instead of combining it to string
  autoload/lsp.vim
  autoload/lsp/client.vim
Labels: perf

#1139 Add LspAddTreeCallHierarchyIncoming
  README.md
  autoload/lsp/ui/vim.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement
