Repository prabirshrestha/vim-lsp, pull requests merged in 2021-01, with the labels that each got.

#996 use callbag share for stream and avoid directly using s:Stream
  autoload/lsp.vim
Labels: bug

#995 Revamp diagnostics highlights
  README.md
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics.vim
  autoload/lsp/internal/diagnostics/document_diagnostics_command.vim
  autoload/lsp/internal/diagnostics/highlights.vim
  autoload/lsp/internal/document_highlight.vim
  autoload/lsp/ui/vim/diagnostics.vim
  autoload/lsp/ui/vim/diagnostics/textprop.vim
  autoload/lsp/ui/vim/highlights.vim
  autoload/lsp/ui/vim/semantic.vim
  autoload/lsp/utils.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: bug, enhancement

#997 refactor diagnostics under cursor to use the new internal diagnostics state
  autoload/lsp/internal/diagnostics/echo.vim
  autoload/lsp/internal/diagnostics/float.vim
  autoload/lsp/internal/diagnostics/under_cursor.vim
  autoload/lsp/ui/vim/code_action.vim
  autoload/lsp/ui/vim/diagnostics.vim
Labels: enhancement

#999 refactor diagnostics count to using diagnostics state
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics/state.vim
  autoload/lsp/ui/vim/diagnostics.vim
  test/lsp/ui/vim/diagnostics.vimspec
Labels: enhancement

#1002 Fix function argument
  autoload/lsp/internal/diagnostics/under_cursor.vim
  autoload/lsp/ui/vim/code_action.vim
Labels: bug

#1003 refactor diagnostics get buffer first error line to use the new internal state
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics/first_line.vim
  autoload/lsp/ui/vim/diagnostics.vim
Labels: enhancement

#1004 Diagnostics move
  autoload/lsp.vim
  autoload/lsp/internal/diagnostics/movement.vim
  autoload/lsp/internal/diagnostics/state.vim
  plugin/lsp.vim
Labels: enhancement

#1006 update callbag to 110c554484bd21520c5f75983f9a3ccd72330018 to support flatMap
  autoload/lsp/callbag.vim
Labels: enhancement

#1007 add support for codeLens/resolve
  autoload/lsp.vim
  autoload/lsp/ui/vim/code_lens.vim
Labels: bug, enhancement

#1008 Fix cursor position calculation on complete done
  autoload/lsp/ui/vim/completion.vim
Labels: bug

#1009 update callbag.vim to 62a31fd03 - adds reduce() operator
  autoload/lsp/callbag.vim
Labels: enhancement

#1012 Fix typos in documents
  README.md
  doc/vim-lsp.txt
Labels: documentation

#1015 add line in codelens
  autoload/lsp/ui/vim/code_lens.vim
Labels: enhancement

#1019 embed quickpick.vim and add experimental quickpick support for codelens
  autoload/lsp/internal/ui/quickpick.vim
  autoload/lsp/ui/vim/code_lens.vim
  plugin/lsp.vim
Labels: enhancement

#1021 start quickpick in insert mode by default - update quickpick to c78c77d6d2b4
  autoload/lsp/internal/ui/quickpick.vim
Labels: bug

#1031 update quickpick to 601f826b829d - do not call mapclear <buffer>
  autoload/lsp/internal/ui/quickpick.vim
Labels: bug

#1029 add LspDocumentSymbolSearch using quickpick
  README.md
  autoload/lsp/internal/document_symbol/search.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#1036 update quickfix to 3c3d58508 - fix vim api update for matchfuzzypos
  autoload/lsp/internal/ui/quickpick.vim
Labels: bug

#1035 Workspace symbol search using quickpick
  autoload/lsp/internal/workspace_symbol/search.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#1038 Improve completion perf
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim/documentation.vim
  autoload/lsp/utils.vim
  test/lsp/omni.vimspec
Labels: enhancement

#1051 fix snippet
  autoload/lsp/omni.vim
  test/lsp/omni.vimspec
Labels: bug

#1033 add vim-vital-vs FloatingWindow
  autoload/vital/_lsp.vim
  autoload/vital/_lsp/VS/Vim/Buffer.vim
  autoload/vital/_lsp/VS/Vim/Window.vim
  autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim
  autoload/vital/lsp.vim
  autoload/vital/lsp.vital
Labels: enhancement

#1046 add support for call hierarchy
  README.md
  autoload/lsp/capabilities.vim
  autoload/lsp/ui/vim.vim
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: enhancement

#1053 default to using quickpick for codelens
  autoload/lsp/ui/vim/code_lens.vim
  plugin/lsp.vim
Labels: enhancement

#1054 update callbag to 72acf412 - fixes undefined l:found
  autoload/lsp/callbag.vim
Labels: bug

#1052 completion/resolve support for documentation and use the new floating window
  autoload/lsp.vim
  autoload/lsp/capabilities.vim
  autoload/lsp/internal/completion/documentation.vim
  autoload/lsp/omni.vim
  autoload/lsp/ui/vim/documentation.vim
  autoload/vital/_lsp/VS/LSP/MarkupContent.vim
  autoload/vital/_lsp/VS/LSP/Text.vim
  autoload/vital/_lsp/VS/Vim/Buffer.vim
  autoload/vital/_lsp/VS/Vim/Syntax/Markdown.vim
  autoload/vital/_lsp/VS/Vim/Window.vim
  autoload/vital/_lsp/VS/Vim/Window/FloatingWindow.vim
  autoload/vital/lsp.vital
  doc/vim-lsp.txt
  plugin/lsp.vim
Labels: documentation
